[build-system]
requires = ["setuptools>=61.0.0", "wheel"] 
build-backend = "setuptools.build_meta"

[project]
name = "quant-dev"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"

# 預留基礎依賴項，有需要可自行追加
dependencies = [ 
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
